version: '2'
services:
  server:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8000
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
      request_line: GET / HTTP/1.0
  agent:
    scale: 1
    start_on_create: true
